iam_role_name = "ssdlc-ai-assist-lambda-role"
iam_policy_name = "ssdlc-ai-assist-lambda-permissions"
s3_bucket_name = "step-function-input-bucket"
s3_object_name = "lambda-layer.zip"
lambda_layer_name = "ssdlc-ai-assist-lambda-layer"
lambda_function_name = "ssdlc-ai-assist-lambda-workflow"